package com.sanluan.cms.entities.cms;

// Generated 2015-5-6 15:49:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CmsChapterAttribute generated by hbm2java
 */
@Entity
@Table(name = "cms_chapter_attribute")
public class CmsChapterAttribute implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int chapterId;
	private String data;
	private String text;
	private int wordCount;

	public CmsChapterAttribute() {
	}

	public CmsChapterAttribute(int chapterId, int wordCount) {
		this.chapterId = chapterId;
		this.wordCount = wordCount;
	}

	public CmsChapterAttribute(int chapterId, String data, String text, int wordCount) {
		this.chapterId = chapterId;
		this.data = data;
		this.text = text;
		this.wordCount = wordCount;
	}

	@Id
	@Column(name = "chapter_id", unique = true, nullable = false)
	public int getChapterId() {
		return this.chapterId;
	}

	public void setChapterId(int chapterId) {
		this.chapterId = chapterId;
	}

	@Column(name = "data", length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "text", length = 65535)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "word_count", nullable = false)
	public int getWordCount() {
		return this.wordCount;
	}

	public void setWordCount(int wordCount) {
		this.wordCount = wordCount;
	}

}
